server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeesystem
    username: root
    password: akhil
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update